server:
  port: 8001

mybatis: 
  type-aliases-package: com.duan.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/*.xml
  
spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root123
    dbcp2: 
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200 
eureka:
  instance:
    prefer-ip-address: true #访问路径是否显示ip    instance-id: microservicecloud-dept8001  #该服务在控制窗口显示的主机名称修改  client:    service-url:      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      #指定erueka注册中心的地址
      defaultZone: http://eureka7001.com:7001/eureka/
info:
  app.name: duan-mocroservicescloud
  com.name: this-is-deal.com
  com.location: CHINA
  bulid.artifactId: ${project.artifactId}
  bulid.version: ${project.version}
      