server:
  port: 7003
eureka:
  server:    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  instance:
    hostname: eureka7003.com
    prefer-ip-address: true
    instance-id: ${spring.cloud.client,ipAddress}${server.port}
  
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/