server:
  port: 7001    #这个是注册中心
eureka:
  server:    enable-self-preservation: false  #自我保护机制
    eviction-interval-timer-in-ms: 5000 #清理间隔,该服务下线以后，服务信息被清理掉的时间。单位是ms
  instance:
    hostname: eureka7001.com
    prefer-ip-address: true  #显示客户机的id
    instance-id: ${spring.cloud.client,ipAddress}${server.port}
  
  client:
    fetch-registry: false
    register-with-eureka: false  #z自己就是注册中心，所以不需要注册到服务中
    service-url:      #defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/  
      defaultZone: http://eureka7001.com:7001/eureka/   #暂时去掉集群，内存限制